// Generates what the site needs from the firmware sources:
//  - src/generated/settings-table.ts from ../src/settings.h (names, defaults, limits, descriptions)
//  - public/s620.bin and public/firmware.json from ../dist
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const header = readFileSync(join(root, "..", "src", "settings.h"), "utf8");

const version = Number(header.match(/#define SETTINGS_VERSION\s+(\d+)/)[1]);
const payload = Number(header.match(/#define SETTINGS_PAYLOAD\s+(\d+)/)[1]);
const rows = [...header.matchAll(/X\((\w+),\s*(\d+),\s*(\d+),\s*(\d+),\s*"([^"]*)"\)/g)].map((m) => ({
  name: m[1],
  def: Number(m[2]),
  min: Number(m[3]),
  max: Number(m[4]),
  description: m[5],
}));
if (rows.length === 0) throw new Error("no settings found in settings.h");

mkdirSync(join(root, "src", "generated"), { recursive: true });
writeFileSync(
  join(root, "src", "generated", "settings-table.ts"),
  `// Generated by scripts/prebuild.mjs from ../src/settings.h. Do not edit.\n` +
    `export const SETTINGS_VERSION = ${version};\n` +
    `export const SETTINGS_PAYLOAD = ${payload};\n` +
    `export const SETTINGS_TABLE = ${JSON.stringify(rows, null, 2)} as const;\n`,
);

// The S620's bootloader (first 16 KB of flash), used by the flasher to recognise the tablet
const boot = readFileSync(join(root, "..", "bootloader", "bootloader_16k.bin"));
writeFileSync(
  join(root, "src", "generated", "known.ts"),
  `// Generated by scripts/prebuild.mjs. Do not edit.
export const S620_BOOTLOADER_SHA256 = "${createHash("sha256").update(boot).digest("hex")}";
`,
);

// The server hands out the firmware images in firmware/ (s620.bin is the build of this repo, s620_original.bin is committed)
const bin = join(root, "..", "dist", "s620.bin");
if (existsSync(bin)) {
  mkdirSync(join(root, "firmware"), { recursive: true });
  copyFileSync(bin, join(root, "firmware", "s620.bin"));
} else {
  console.warn("dist/s620.bin not found: build the firmware first (py build.py)");
}
console.log(`prebuild: ${rows.length} settings, version ${version}`);
